# -*- coding: utf-8 -*-
"""Human Activity Recognition Using Machine Learning and Deep Learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b6u_i559sHyirYUWM26gM2uRlJBAk4tD

## **Human Activity Recognition Using Machine Learning and Deep Learning**

**Importing Relevant Libraries**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.utils import to_categorical

"""**Loading The Files**"""

train = pd.read_csv("/content/test.csv")
test = pd.read_csv("/content/train.csv")

print("Train shape:", train.shape)
print("Test shape:", test.shape)

train.head()

"""**Check the activity classes**"""

print(train["Activity"].value_counts())

"""**Split features and target**"""

X_train = train.drop(columns=["Activity"])
y_train = train["Activity"]

X_test = test.drop(columns=["Activity"])
y_test = test["Activity"]

"""**Encode target labels**"""

encoder = LabelEncoder()

y_train_encoded = encoder.fit_transform(y_train)
y_test_encoded = encoder.transform(y_test)

print(encoder.classes_)

"""**Scale the features**"""

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

"""**Baseline model — Logistic Regression:**"""

lr = LogisticRegression(max_iter=2000)

lr.fit(X_train_scaled, y_train_encoded)

y_pred_lr = lr.predict(X_test_scaled)

print("Logistic Regression Accuracy:", accuracy_score(y_test_encoded, y_pred_lr))
print(classification_report(y_test_encoded, y_pred_lr, target_names=encoder.classes_))

"""**Baseline model — Random Forest**"""

rf = RandomForestClassifier(n_estimators=200, random_state=42)

rf.fit(X_train, y_train_encoded)

y_pred_rf = rf.predict(X_test)

print("Random Forest Accuracy:", accuracy_score(y_test_encoded, y_pred_rf))
print(classification_report(y_test_encoded, y_pred_rf, target_names=encoder.classes_))

"""**LSTM preparation**"""

X_train_lstm = X_train_scaled.reshape((X_train_scaled.shape[0], 1, X_train_scaled.shape[1]))
X_test_lstm = X_test_scaled.reshape((X_test_scaled.shape[0], 1, X_test_scaled.shape[1]))

y_train_cat = to_categorical(y_train_encoded)
y_test_cat = to_categorical(y_test_encoded)

"""**Build LSTM model**"""

model = Sequential([
    LSTM(64, input_shape=(X_train_lstm.shape[1], X_train_lstm.shape[2])),
    Dropout(0.3),
    Dense(32, activation="relu"),
    Dense(6, activation="softmax")
])

model.compile(
    optimizer="adam",
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

model.summary()

"""**Train LSTM**"""

history = model.fit(
    X_train_lstm,
    y_train_cat,
    epochs=10,
    batch_size=64,
    validation_data=(X_test_lstm, y_test_cat)
)

"""**Evaluate LSTM**"""

loss, accuracy = model.evaluate(X_test_lstm, y_test_cat)
print("LSTM Accuracy:", accuracy)

"""**Confusion matrix for LSTM**"""

y_pred_lstm_prob = model.predict(X_test_lstm)
y_pred_lstm = np.argmax(y_pred_lstm_prob, axis=1)

cm = confusion_matrix(y_test_encoded, y_pred_lstm)

plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt="d", xticklabels=encoder.classes_, yticklabels=encoder.classes_)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("LSTM Confusion Matrix - Human Activity Recognition")
plt.xticks(rotation=45)
plt.yticks(rotation=0)
plt.show()